#!/usr/bin/env python3
"""Generate K8s NetworkPolicies from the topology in deploy/policies.yaml.

One source of truth for "who talks to whom": the same file the harness policy
engine reads. Output is checked in at deploy/chart/templates/networkpolicies.yaml;
CI fails if it drifts from the topology (see tests/test_topology_sync.py).

Model: default-deny all ingress+egress in the namespace, then one policy per
service allowing exactly its declared edges, DNS for everyone, external
ingress/egress only where the topology says so.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
POLICIES = ROOT / "deploy" / "policies.yaml"
OUTPUT = ROOT / "deploy" / "chart" / "templates" / "networkpolicies.yaml"

HEADER = "# GENERATED by scripts/gen_networkpolicies.py from deploy/policies.yaml — do not edit.\n"

DNS_EGRESS = {
    "to": [{"namespaceSelector": {}, "podSelector": {"matchLabels": {"k8s-app": "kube-dns"}}}],
    "ports": [{"protocol": "UDP", "port": 53}, {"protocol": "TCP", "port": 53}],
}


def _policy(name: str, spec: dict) -> dict:
    return {
        "apiVersion": "networking.k8s.io/v1",
        "kind": "NetworkPolicy",
        "metadata": {"name": name},
        "spec": spec,
    }


def build(topology: dict) -> list[dict]:
    services: dict = topology["services"]
    edges: dict = topology["edges"]
    inbound: dict[str, list[str]] = {name: [] for name in services}
    for source, targets in edges.items():
        for target in targets:
            inbound[target].append(source)

    documents = [
        _policy(
            "default-deny",
            {"podSelector": {}, "policyTypes": ["Ingress", "Egress"], "egress": [DNS_EGRESS]},
        )
    ]

    for name, meta in services.items():
        spec: dict = {
            "podSelector": {"matchLabels": {"app": name}},
            "policyTypes": ["Ingress", "Egress"],
        }

        ingress = []
        if inbound[name]:
            ingress.append(
                {
                    "from": [
                        {"podSelector": {"matchLabels": {"app": source}}}
                        for source in sorted(inbound[name])
                    ],
                    "ports": [{"protocol": "TCP", "port": meta["port"]}],
                }
            )
        if meta.get("external_ingress"):
            ingress.append({"ports": [{"protocol": "TCP", "port": meta["port"]}]})
        if ingress:
            spec["ingress"] = ingress

        egress = [DNS_EGRESS]
        for target in sorted(edges.get(name, [])):
            egress.append(
                {
                    "to": [{"podSelector": {"matchLabels": {"app": target}}}],
                    "ports": [{"protocol": "TCP", "port": services[target]["port"]}],
                }
            )
        if meta.get("internet_egress"):
            egress.append(
                {
                    "to": [
                        {
                            "ipBlock": {
                                "cidr": "0.0.0.0/0",
                                "except": ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"],
                            }
                        }
                    ],
                    "ports": [{"protocol": "TCP", "port": 443}],
                }
            )
        spec["egress"] = egress

        documents.append(_policy(f"allow-{name}", spec))
    return documents


def render(topology: dict) -> str:
    return HEADER + "---\n".join(yaml.safe_dump(doc, sort_keys=False) for doc in build(topology))


def main() -> int:
    topology = yaml.safe_load(POLICIES.read_text())["topology"]
    rendered = render(topology)
    if "--check" in sys.argv:
        if OUTPUT.read_text() != rendered:
            print(
                "networkpolicies.yaml is out of sync with policies.yaml topology", file=sys.stderr
            )
            return 1
        print("networkpolicies.yaml in sync")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
