#!/usr/bin/env python3
"""Pin the first-party MCP servers' tool manifests into deploy/policies.yaml.

Hashes are computed in-process from the server objects (no network), so the
pin reflects exactly the code that will be deployed. Run after any change to
a tool's name, description, or signature; `--check` fails if the file is
stale (wired into CI next to the NetworkPolicy drift check).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import anyio

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from triage_mesh.harness.integrity import manifest_hash  # noqa: E402
from triage_mesh.mcp_servers import repo_reader, report_writer, vuln_intel  # noqa: E402

POLICIES = ROOT / "deploy" / "policies.yaml"
SERVERS = {
    "repo-reader": repo_reader.server,
    "vuln-intel": vuln_intel.server,
    "report-writer": report_writer.server,
}
BEGIN = "# --- tool_integrity (generated by scripts/pin_tools.py; do not edit) ---"
END = "# --- end tool_integrity ---"


async def compute() -> dict[str, str]:
    return {name: manifest_hash(await server.list_tools()) for name, server in SERVERS.items()}


def render(hashes: dict[str, str]) -> str:
    lines = [BEGIN, "tool_integrity:"]
    lines += [f"  {name}: {digest}" for name, digest in hashes.items()]
    lines.append(END)
    return "\n".join(lines) + "\n"


def main() -> int:
    hashes = anyio.run(compute)
    block = render(hashes)
    text = POLICIES.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n", re.DOTALL)
    if pattern.search(text):
        updated = pattern.sub(block, text)
    else:
        updated = text.rstrip("\n") + "\n\n" + block

    if "--check" in sys.argv:
        if updated != text:
            print("tool_integrity pins are stale — run scripts/pin_tools.py", file=sys.stderr)
            return 1
        print("tool_integrity pins in sync")
        return 0
    POLICIES.write_text(updated, encoding="utf-8")
    for name, digest in hashes.items():
        print(f"pinned {name}: {digest[:16]}…")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
